# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,

                      - nazwa: Konfiguracja środowiska Node.js
  używa: actions/setup-node@v3.9.1
  z:
    # Ustaw always-authentication w npmrc.
    always-auth: # opcjonalnie, domyślnie false
    # Specyfikacja wersji do użycia. Przykłady: 12.x, 10.15.1, >=10.15.0.
    node-version: # opcjonalnie
    # Plik zawierający specyfikację wersji do użycia. Przykłady: .nvmrc, .node-version, .tool-versions.
    node-version-file: # opcjonalnie
    # Docelowa architektura, której Node ma używać. Przykłady: x86, x64. Domyślnie będzie używana architektura systemowa.
    architektura: # opcjonalnie
    # Ustaw tę opcję, jeśli chcesz, aby akcja sprawdzała, czy dostępna jest najnowsza wersja spełniająca specyfikację wersji.
    sprawdź-najnowsze: #opcjonalne
    # Opcjonalny rejestr do skonfigurowania dla uwierzytelniania. Ustawi rejestr w pliku .npmrc i .yarnrc na poziomie projektu i skonfiguruje uwierzytelnianie do odczytu z env.NODE_AUTH_TOKEN.
    registry-url: # opcjonalnie
    # Opcjonalny zakres uwierzytelniania względem rejestrów o określonym zakresie. W przypadku korzystania z rejestru GitHub Packages (https://npm.pkg.github.com/) nastąpi powrót do właściciela repozytorium.
    zakres: # opcjonalny
    # Służy do pobierania dystrybucji węzłów z wersji węzłów. Ponieważ istnieje wartość domyślna, użytkownik zazwyczaj jej nie dostarcza. Podczas uruchamiania tej akcji na github.com wartość domyślna jest wystarczająca. Podczas uruchamiania na GHES możesz przekazać osobisty token dostępu dla github.com, jeśli występuje ograniczenie szybkości.
    token: # opcjonalny, domyślnie ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Służy do określania menedżera pakietów do buforowania w domyślnym katalogu. Obsługiwane wartości: npm, yarn, pnpm.
    pamięć podręczna: # opcjonalnie
    # Służy do określania ścieżki do pliku zależności: package-lock.json, yarn.lock itd. Obsługuje symbole wieloznaczne lub listę nazw plików w celu buforowania wielu zależności.
    ścieżka-zależności-pamięci-podręcznej: # opcjonalnie
          
          echo test, and deploy your project.
